docs_dir: content
nav:
- Home: index.md
- Task Overview: task.md
- Approach Overview: approach.md
- Results: results.md
- Model API Reference: model-api-reference.md
- Data API Reference: data-api-reference.md
site_name: Intent and Entity Classifier
theme:
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  name: material
