docs_dir: content
nav:
- Home: index.md
- Task Overview: task.md
- Approach Overview: approach.md
- Results: results.md
- API Reference: api-reference.md
site_name: Intent and Entity Classifier
theme: material
